name: Job concurrency (eg)

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    concurrency:
      group: deploy
      cancel-in-progress: true

    steps:
      - name: Hello
        run: echo "Hii all"
